### ISSUE TITLE
AttributeError: 'super' object has no attribute 'init'

### ISSUE THREAD

**Issue by murphy2712** [bitrate16/peripage-python#15]
Hi,
I installed the updated repo (from ppa6 naming which was printing fine) and executed the requirement installs, but executing the peripage.py command now gives me this error:

```
$ python3 peripage.py -m myprinteradress -p A6p -t test
Traceback (most recent call last):
  File "/Users/xxx/Personal/peripage-python-main/peripage.py", line 10, in <module>
    main()
  File "/Users/xxx/Personal/peripage-python-main/peripage/__main__.py", line 76, in main
    printer.connect()
  File "/Users/xxx/Personal/peripage-python-main/peripage/__init__.py", line 156, in connect
    self.sock.connect((self.mac, 1))
  File "/opt/homebrew/lib/python3.11/site-packages/bluetooth/macos.py", line 119, in connect
    return self._sock.connect(addrport)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/lightblue/_bluetoothsockets.py", line 348, in connect
    self.__eventlistener = self.__createlistener()
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/lightblue/_bluetoothsockets.py", line 642, in __createlistener
    listener = _ChannelEventListener.alloc().initWithDelegate_(self)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/lightblue/_bluetoothsockets.py", line 787, in initWithDelegate_
    self = super().init()
           ^^^^^^^^^^^^
AttributeError: 'super' object has no attribute 'init'
sys:1: UninitializedDeallocWarning: leaking an uninitialized object of type _ChannelEventListener
```

I'm running on a Mac M1 with Ventura 13.3.1.
Thanks for the help.

**Comment by kkogggokk** [comment]
MacOS : 12.6.7
Python : 3.10.11 
I installed it through pip install ppa6. 
But I have a similar issue.
<img width="1500" alt="스크린샷 2023-06-25 오전 2 05 55" src="https://github.com/bitrate16/peripage-python/assets/68055218/e7c0981e-4bec-42d7-89a1-b7854406daf1">

`[/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_macutil.py:169](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_macutil.py:169): ObjCSuperWarning: Objective-C subclass uses super(), but super is not objc.super
  class BBCocoaSleeper(NSObject):
[/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_macutil.py:192](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_macutil.py:192): ObjCSuperWarning: Objective-C subclass uses super(), but super is not objc.super
  class BBFileLikeObjectReader(NSObject):
[/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_macutil.py:218](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_macutil.py:218): ObjCSuperWarning: Objective-C subclass uses super(), but super is not objc.super
  class BBFileLikeObjectWriter(NSObject):
[/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_bluetoothsockets.py:760](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_bluetoothsockets.py:760): ObjCSuperWarning: Objective-C subclass uses super(), but super is not objc.super
  class _ChannelEventListener(Foundation.NSObject):
[/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_bluetoothsockets.py:834](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_bluetoothsockets.py:834): ObjCSuperWarning: Objective-C subclass uses super(), but super is not objc.super
  class _ChannelServerEventListener(Foundation.NSObject):
[/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_obex.py:338](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_obex.py:338): ObjCSuperWarning: Objective-C subclass uses super(), but super is not objc.super
  class _BBOBEXClientDelegate(NSObject):
[/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_obex.py:447](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_obex.py:447): ObjCSuperWarning: Objective-C subclass uses super(), but super is not objc.super
  class BBOBEXObjectPushServer(NSObject):
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 5
      2 import peripage
      4 printer = peripage.Printer('C5:5C:1A:10:41:B8', peripage.PrinterType.A6p)
----> 5 printer.connect()
      6 printer.reset()

File [~/.local/lib/python3.10/site-packages/peripage/__init__.py:156](https://file+.vscode-resource.vscode-cdn.net/Users/master90/Downloads/peripage-python-main/peripage-python-main/notebooks/~/.local/lib/python3.10/site-packages/peripage/__init__.py:156), in Printer.connect(self)
    146 """
    147 Open a new connection to the printer without checking for existing
    148 connection. In case of malfunction and/or twice connecting to the same
   (...)
    152 `reset()` after connecting.
    153 """
    155 self.sock = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
--> 156 self.sock.connect((self.mac, 1))
    157 self.sock.settimeout(self.timeout)

File [/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/bluetooth/macos.py:119](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/bluetooth/macos.py:119), in BluetoothSocket.connect(self, addrport)
    118 def connect(self, addrport):
--> 119     return self._sock.connect(addrport)

File [/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_bluetoothsockets.py:348](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/ppa6/lib/python3.10/site-packages/lightblue/_bluetoothsockets.py:348), in _BluetoothSocket.connect(self, address)
    343             raise _socket.error(result,
...
--> 787     self = super().init()
    788     if cb_obj is None:
    789         raise TypeError("callback object is None")

AttributeError: 'super' object has no attribute 'init'`

**Comment by kkogggokk** [comment]
MacOS : 12.6.7
Python : 3.10.11 
I installed it through pip install peripage
But I have a similar issue.
<img width="1342" alt="스크린샷 2023-06-25 오전 2 22 22" src="https://github.com/bitrate16/peripage-python/assets/68055218/e45fc4ae-b6e7-47f3-bd63-df53389d6df9">

<img width="359" alt="스크린샷 2023-06-25 오전 2 24 25" src="https://github.com/bitrate16/peripage-python/assets/68055218/94a27743-fc7c-41a1-98d4-41a5e6977099">

**Comment by bitrate16** [comment]
@murphy2712 @kkogggokk have you tried to install latest bluez library from original repo? https://github.com/pybluez/pybluez

`pip install git+https://github.com/pybluez/pybluez@master#egg=pybluez --user`

I currently can not test it without hardware
